language: cpp

addons:
    apt_packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libvorbis-dev
    - g++
    - clang
    - libgl1-mesa-dev
    - curl

matrix:
    include:
        - name: "Linux GCC"
          compiler: gcc
          sudo:     required
          os:       linux
          dist:     xenial

        - name: "Linux Clang"
          compiler: clang
          sudo:     required
          os:       linux
          dist:     xenial

before_script:
    - git clone https://github.com/SFML/SFML.git
    - cd SFML
    - mkdir build
    - cd build
    - >
      cmake
      -DSFML_BUILD_EXAMPLES=FALSE
      -DSFML_BUILD_DOC=FALSE
      -DSFML_BUILD_AUDIO=FALSE
      -DSFML_BUILD_GRAPHICS=TRUE
      -DSFML_BUILD_WINDOW=TRUE
      -DSFML_BUILD_NETWORK=FALSE
      ..
    - cmake --build .
    - sudo make install
    - cd ../..
    - git clone https://github.com/TankOs/SFGUI.git
    - cd SFGUI
    - sed '138{s/^/#/}' CMakeLists.txt > tmp    # hack to disable SFGUI warnings
    - mv tmp CMakeLists.txt                     #
    - mkdir build
    - cd build
    - cmake -DSFGUI_BUILD_EXAMPLES=OFF ..
    - cmake --build .
    - sudo make install
    - cd ../..
    - wget https://hyperrealm.github.io/libconfig/dist/libconfig-1.7.2.tar.gz
    - tar -xzf libconfig-1.7.2.tar.gz
    - cd libconfig-1.7.2
    - ./configure
    - make
    - sudo make install
    - cd ..
    - mkdir build
    - cd build

script:
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..
    - cmake --build .

after_script:
    - sudo make install

notifications:
    email: false
