language: cpp

addons:
    apt_packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libvorbis-dev
    - g++
    - clang
    - libgl1-mesa-dev
    - libjsoncpp-dev
    - curl
    - fakeroot
    - hashdeep

os: linux

jobs:
    include:
        - name: "Linux GCC"
          compiler: gcc
          dist:     bionic
          env:
          - DEPLOY=TRUE

        - name: "Linux Clang"
          compiler: clang
          dist:     bionic

        - name: "Windows static cross-compile"
          compiler: gcc
          dist:     bionic
          env:
          - WINDOWS=TRUE
          - DEPLOY=TRUE

before_script:
    - source scripts/before_script.sh

script:
    - source scripts/script.sh

before_deploy:
    - source scripts/before_deploy.sh

deploy:
    provider: releases
    token: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: deploy/*
    skip_cleanup: true
    draft: true
    on:
        condition: $DEPLOY = TRUE

notifications:
    email: false
