language: cpp

addons:
    apt_packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libvorbis-dev
    - g++
    - clang
    - libgl1-mesa-dev
    - libconfig++-dev
    - curl
    - fakeroot
    - hashdeep

os: linux

jobs:
    include:
        - name: "Linux GCC"
          compiler: gcc
          dist:     bionic

        - name: "Linux Clang"
          compiler: clang
          dist:     bionic

before_script:
    - echo "deb http://us.archive.ubuntu.com/ubuntu/ disco universe" >> /etc/apt/sources.list
    - sudo apt update
    - sudo apt install libsfml-dev
    - git clone https://github.com/TankOs/SFGUI.git
    - cd SFGUI
    - sed '138{s/^/#/}' CMakeLists.txt > tmp    # hack to disable SFGUI warnings
    - mv tmp CMakeLists.txt                     #
    - mkdir build
    - cd build
    - cmake -DSFGUI_BUILD_EXAMPLES=OFF ..
    - cmake --build .
    - sudo make install
    - cd ../..
    - mkdir build
    - cd build

script:
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..
    - cmake --build .
    - sudo make install

before_deploy:
    - cd ../deb
    - mkdir opt
    - cp -r /opt/mazemaze opt
    - mkdir -p usr/share/applications/
    - cp ~/.local/share/applications/mazemaze.desktop usr/share/applications/
    - md5deep -rl opt usr > DEBIAN/md5sums
    - cat DEBIAN/md5sums
    - cd ..
    - fakeroot dpkg-deb --build deb
    - mv deb.deb mazemaze_0.2_amd64.deb

deploy:
    provider: releases
    token: $GITHUB_OAUTH_TOKEN
    file: mazemaze_0.2_amd64.deb
    skip_cleanup: true
    draft: true
    on:
        condition: $CC = gcc

notifications:
    email: false
